---
- hosts: all
  become: true
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - yum-utils
  
    - name: Install Docker
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
            - docker

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes
...
        
